/*
Copyright (c) 2015, Northeastern University
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Northeastern University nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL Northeastern University BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/controllerapi/controllerapi.proto
// DO NOT EDIT!

/*
Package controllerapi is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/controllerapi/controllerapi.proto

It has these top-level messages:
*/
package controllerapi

import proto "github.com/golang/protobuf/proto"
import datamodel2 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel3 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel4 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel5 "github.com/NEU-SNS/ReverseTraceroute/datamodel"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// Client API for Controller service

type ControllerClient interface {
	Ping(ctx context.Context, in *datamodel2.PingArg, opts ...grpc.CallOption) (Controller_PingClient, error)
	Traceroute(ctx context.Context, in *datamodel3.TracerouteArg, opts ...grpc.CallOption) (Controller_TracerouteClient, error)
	GetVPs(ctx context.Context, in *datamodel4.VPRequest, opts ...grpc.CallOption) (*datamodel4.VPReturn, error)
	ReceiveSpoofedProbes(ctx context.Context, opts ...grpc.CallOption) (Controller_ReceiveSpoofedProbesClient, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Ping(ctx context.Context, in *datamodel2.PingArg, opts ...grpc.CallOption) (Controller_PingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[0], c.cc, "/.Controller/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_PingClient interface {
	Recv() (*datamodel2.Ping, error)
	grpc.ClientStream
}

type controllerPingClient struct {
	grpc.ClientStream
}

func (x *controllerPingClient) Recv() (*datamodel2.Ping, error) {
	m := new(datamodel2.Ping)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) Traceroute(ctx context.Context, in *datamodel3.TracerouteArg, opts ...grpc.CallOption) (Controller_TracerouteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[1], c.cc, "/.Controller/Traceroute", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerTracerouteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_TracerouteClient interface {
	Recv() (*datamodel3.Traceroute, error)
	grpc.ClientStream
}

type controllerTracerouteClient struct {
	grpc.ClientStream
}

func (x *controllerTracerouteClient) Recv() (*datamodel3.Traceroute, error) {
	m := new(datamodel3.Traceroute)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) GetVPs(ctx context.Context, in *datamodel4.VPRequest, opts ...grpc.CallOption) (*datamodel4.VPReturn, error) {
	out := new(datamodel4.VPReturn)
	err := grpc.Invoke(ctx, "/.Controller/GetVPs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReceiveSpoofedProbes(ctx context.Context, opts ...grpc.CallOption) (Controller_ReceiveSpoofedProbesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[2], c.cc, "/.Controller/ReceiveSpoofedProbes", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerReceiveSpoofedProbesClient{stream}
	return x, nil
}

type Controller_ReceiveSpoofedProbesClient interface {
	Send(*datamodel5.Probe) error
	CloseAndRecv() (*datamodel5.ReceiveSpoofedProbesResponse, error)
	grpc.ClientStream
}

type controllerReceiveSpoofedProbesClient struct {
	grpc.ClientStream
}

func (x *controllerReceiveSpoofedProbesClient) Send(m *datamodel5.Probe) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerReceiveSpoofedProbesClient) CloseAndRecv() (*datamodel5.ReceiveSpoofedProbesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(datamodel5.ReceiveSpoofedProbesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Controller service

type ControllerServer interface {
	Ping(*datamodel2.PingArg, Controller_PingServer) error
	Traceroute(*datamodel3.TracerouteArg, Controller_TracerouteServer) error
	GetVPs(context.Context, *datamodel4.VPRequest) (*datamodel4.VPReturn, error)
	ReceiveSpoofedProbes(Controller_ReceiveSpoofedProbesServer) error
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel2.PingArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Ping(m, &controllerPingServer{stream})
}

type Controller_PingServer interface {
	Send(*datamodel2.Ping) error
	grpc.ServerStream
}

type controllerPingServer struct {
	grpc.ServerStream
}

func (x *controllerPingServer) Send(m *datamodel2.Ping) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel3.TracerouteArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Traceroute(m, &controllerTracerouteServer{stream})
}

type Controller_TracerouteServer interface {
	Send(*datamodel3.Traceroute) error
	grpc.ServerStream
}

type controllerTracerouteServer struct {
	grpc.ServerStream
}

func (x *controllerTracerouteServer) Send(m *datamodel3.Traceroute) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_GetVPs_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(datamodel4.VPRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(ControllerServer).GetVPs(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Controller_ReceiveSpoofedProbes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).ReceiveSpoofedProbes(&controllerReceiveSpoofedProbesServer{stream})
}

type Controller_ReceiveSpoofedProbesServer interface {
	SendAndClose(*datamodel5.ReceiveSpoofedProbesResponse) error
	Recv() (*datamodel5.Probe, error)
	grpc.ServerStream
}

type controllerReceiveSpoofedProbesServer struct {
	grpc.ServerStream
}

func (x *controllerReceiveSpoofedProbesServer) SendAndClose(m *datamodel5.ReceiveSpoofedProbesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerReceiveSpoofedProbesServer) Recv() (*datamodel5.Probe, error) {
	m := new(datamodel5.Probe)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: ".Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVPs",
			Handler:    _Controller_GetVPs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _Controller_Ping_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _Controller_Traceroute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveSpoofedProbes",
			Handler:       _Controller_ReceiveSpoofedProbes_Handler,
			ClientStreams: true,
		},
	},
}
