/*
Copyright (c) 2015, Northeastern University
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Northeastern University nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL Northeastern University BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/plcontrollerapi/plcontrollerapi.proto
// DO NOT EDIT!

/*
Package plcontrollerapi is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/plcontrollerapi/plcontrollerapi.proto

It has these top-level messages:
*/
package plcontrollerapi

import proto "github.com/golang/protobuf/proto"
import datamodel2 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel4 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel5 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel6 "github.com/NEU-SNS/ReverseTraceroute/datamodel"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

func init() {
}

// Client API for PLController service

type PLControllerClient interface {
	Ping(ctx context.Context, in *datamodel2.PingArg, opts ...grpc.CallOption) (PLController_PingClient, error)
	Traceroute(ctx context.Context, in *datamodel4.TracerouteArg, opts ...grpc.CallOption) (PLController_TracerouteClient, error)
	ReceiveSpoof(ctx context.Context, in *datamodel6.RecSpoof, opts ...grpc.CallOption) (PLController_ReceiveSpoofClient, error)
	GetVPs(ctx context.Context, in *datamodel5.VPRequest, opts ...grpc.CallOption) (PLController_GetVPsClient, error)
}

type pLControllerClient struct {
	cc *grpc.ClientConn
}

func NewPLControllerClient(cc *grpc.ClientConn) PLControllerClient {
	return &pLControllerClient{cc}
}

func (c *pLControllerClient) Ping(ctx context.Context, in *datamodel2.PingArg, opts ...grpc.CallOption) (PLController_PingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[0], c.cc, "/.PLController/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_PingClient interface {
	Recv() (*datamodel2.Ping, error)
	grpc.ClientStream
}

type pLControllerPingClient struct {
	grpc.ClientStream
}

func (x *pLControllerPingClient) Recv() (*datamodel2.Ping, error) {
	m := new(datamodel2.Ping)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) Traceroute(ctx context.Context, in *datamodel4.TracerouteArg, opts ...grpc.CallOption) (PLController_TracerouteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[1], c.cc, "/.PLController/Traceroute", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerTracerouteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_TracerouteClient interface {
	Recv() (*datamodel4.Traceroute, error)
	grpc.ClientStream
}

type pLControllerTracerouteClient struct {
	grpc.ClientStream
}

func (x *pLControllerTracerouteClient) Recv() (*datamodel4.Traceroute, error) {
	m := new(datamodel4.Traceroute)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) ReceiveSpoof(ctx context.Context, in *datamodel6.RecSpoof, opts ...grpc.CallOption) (PLController_ReceiveSpoofClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[2], c.cc, "/.PLController/ReceiveSpoof", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerReceiveSpoofClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_ReceiveSpoofClient interface {
	Recv() (*datamodel6.NotifyRecSpoofResponse, error)
	grpc.ClientStream
}

type pLControllerReceiveSpoofClient struct {
	grpc.ClientStream
}

func (x *pLControllerReceiveSpoofClient) Recv() (*datamodel6.NotifyRecSpoofResponse, error) {
	m := new(datamodel6.NotifyRecSpoofResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) GetVPs(ctx context.Context, in *datamodel5.VPRequest, opts ...grpc.CallOption) (PLController_GetVPsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[3], c.cc, "/.PLController/GetVPs", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerGetVPsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_GetVPsClient interface {
	Recv() (*datamodel5.VPReturn, error)
	grpc.ClientStream
}

type pLControllerGetVPsClient struct {
	grpc.ClientStream
}

func (x *pLControllerGetVPsClient) Recv() (*datamodel5.VPReturn, error) {
	m := new(datamodel5.VPReturn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PLController service

type PLControllerServer interface {
	Ping(*datamodel2.PingArg, PLController_PingServer) error
	Traceroute(*datamodel4.TracerouteArg, PLController_TracerouteServer) error
	ReceiveSpoof(*datamodel6.RecSpoof, PLController_ReceiveSpoofServer) error
	GetVPs(*datamodel5.VPRequest, PLController_GetVPsServer) error
}

func RegisterPLControllerServer(s *grpc.Server, srv PLControllerServer) {
	s.RegisterService(&_PLController_serviceDesc, srv)
}

func _PLController_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel2.PingArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).Ping(m, &pLControllerPingServer{stream})
}

type PLController_PingServer interface {
	Send(*datamodel2.Ping) error
	grpc.ServerStream
}

type pLControllerPingServer struct {
	grpc.ServerStream
}

func (x *pLControllerPingServer) Send(m *datamodel2.Ping) error {
	return x.ServerStream.SendMsg(m)
}

func _PLController_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel4.TracerouteArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).Traceroute(m, &pLControllerTracerouteServer{stream})
}

type PLController_TracerouteServer interface {
	Send(*datamodel4.Traceroute) error
	grpc.ServerStream
}

type pLControllerTracerouteServer struct {
	grpc.ServerStream
}

func (x *pLControllerTracerouteServer) Send(m *datamodel4.Traceroute) error {
	return x.ServerStream.SendMsg(m)
}

func _PLController_ReceiveSpoof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel6.RecSpoof)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).ReceiveSpoof(m, &pLControllerReceiveSpoofServer{stream})
}

type PLController_ReceiveSpoofServer interface {
	Send(*datamodel6.NotifyRecSpoofResponse) error
	grpc.ServerStream
}

type pLControllerReceiveSpoofServer struct {
	grpc.ServerStream
}

func (x *pLControllerReceiveSpoofServer) Send(m *datamodel6.NotifyRecSpoofResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PLController_GetVPs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel5.VPRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).GetVPs(m, &pLControllerGetVPsServer{stream})
}

type PLController_GetVPsServer interface {
	Send(*datamodel5.VPReturn) error
	grpc.ServerStream
}

type pLControllerGetVPsServer struct {
	grpc.ServerStream
}

func (x *pLControllerGetVPsServer) Send(m *datamodel5.VPReturn) error {
	return x.ServerStream.SendMsg(m)
}

var _PLController_serviceDesc = grpc.ServiceDesc{
	ServiceName: ".PLController",
	HandlerType: (*PLControllerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _PLController_Ping_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _PLController_Traceroute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveSpoof",
			Handler:       _PLController_ReceiveSpoof_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetVPs",
			Handler:       _PLController_GetVPs_Handler,
			ServerStreams: true,
		},
	},
}
