#!/bin/bash
# Precommit script

#Add license to go files if they don't have it and abort so they can be staged

LICENSE='./LICENSE'
RETURN=0
FILES=""

for i in `(find . -type f -name "*.go")` 
do
   if  ! grep -q "Copyright (c) 2015, Northeastern University" $i 
   then
       cat $LICENSE $i > $i.new
       mv $i.new $i 
       FILES=$FILES" $i"
       RETURN=1
   fi
done
if  [ "${RETURN}" -eq 1 ]
then
    cat <<\EOF
    License info was missing from source files.
    Added license to source files.
EOF
fi
    if [[ -n $FILES ]]
        then
            git add $FILES
    fi
exit 0


