// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/plcontroller/pb/plcontrollerapi.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/plcontroller/pb/plcontrollerapi.proto

It has these top-level messages:
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import datamodel1 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel2 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel3 "github.com/NEU-SNS/ReverseTraceroute/datamodel"
import datamodel4 "github.com/NEU-SNS/ReverseTraceroute/datamodel"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PLController service

type PLControllerClient interface {
	Ping(ctx context.Context, opts ...grpc.CallOption) (PLController_PingClient, error)
	Traceroute(ctx context.Context, opts ...grpc.CallOption) (PLController_TracerouteClient, error)
	ReceiveSpoof(ctx context.Context, in *datamodel4.RecSpoof, opts ...grpc.CallOption) (PLController_ReceiveSpoofClient, error)
	GetVPs(ctx context.Context, in *datamodel3.VPRequest, opts ...grpc.CallOption) (PLController_GetVPsClient, error)
	AcceptProbes(ctx context.Context, in *datamodel4.SpoofedProbes, opts ...grpc.CallOption) (*datamodel4.SpoofedProbesResponse, error)
}

type pLControllerClient struct {
	cc *grpc.ClientConn
}

func NewPLControllerClient(cc *grpc.ClientConn) PLControllerClient {
	return &pLControllerClient{cc}
}

func (c *pLControllerClient) Ping(ctx context.Context, opts ...grpc.CallOption) (PLController_PingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[0], c.cc, "/PLController/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerPingClient{stream}
	return x, nil
}

type PLController_PingClient interface {
	Send(*datamodel1.PingArg) error
	Recv() (*datamodel1.Ping, error)
	grpc.ClientStream
}

type pLControllerPingClient struct {
	grpc.ClientStream
}

func (x *pLControllerPingClient) Send(m *datamodel1.PingArg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pLControllerPingClient) Recv() (*datamodel1.Ping, error) {
	m := new(datamodel1.Ping)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) Traceroute(ctx context.Context, opts ...grpc.CallOption) (PLController_TracerouteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[1], c.cc, "/PLController/Traceroute", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerTracerouteClient{stream}
	return x, nil
}

type PLController_TracerouteClient interface {
	Send(*datamodel2.TracerouteArg) error
	Recv() (*datamodel2.Traceroute, error)
	grpc.ClientStream
}

type pLControllerTracerouteClient struct {
	grpc.ClientStream
}

func (x *pLControllerTracerouteClient) Send(m *datamodel2.TracerouteArg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pLControllerTracerouteClient) Recv() (*datamodel2.Traceroute, error) {
	m := new(datamodel2.Traceroute)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) ReceiveSpoof(ctx context.Context, in *datamodel4.RecSpoof, opts ...grpc.CallOption) (PLController_ReceiveSpoofClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[2], c.cc, "/PLController/ReceiveSpoof", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerReceiveSpoofClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_ReceiveSpoofClient interface {
	Recv() (*datamodel4.NotifyRecSpoofResponse, error)
	grpc.ClientStream
}

type pLControllerReceiveSpoofClient struct {
	grpc.ClientStream
}

func (x *pLControllerReceiveSpoofClient) Recv() (*datamodel4.NotifyRecSpoofResponse, error) {
	m := new(datamodel4.NotifyRecSpoofResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) GetVPs(ctx context.Context, in *datamodel3.VPRequest, opts ...grpc.CallOption) (PLController_GetVPsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PLController_serviceDesc.Streams[3], c.cc, "/PLController/GetVPs", opts...)
	if err != nil {
		return nil, err
	}
	x := &pLControllerGetVPsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PLController_GetVPsClient interface {
	Recv() (*datamodel3.VPReturn, error)
	grpc.ClientStream
}

type pLControllerGetVPsClient struct {
	grpc.ClientStream
}

func (x *pLControllerGetVPsClient) Recv() (*datamodel3.VPReturn, error) {
	m := new(datamodel3.VPReturn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pLControllerClient) AcceptProbes(ctx context.Context, in *datamodel4.SpoofedProbes, opts ...grpc.CallOption) (*datamodel4.SpoofedProbesResponse, error) {
	out := new(datamodel4.SpoofedProbesResponse)
	err := grpc.Invoke(ctx, "/PLController/AcceptProbes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PLController service

type PLControllerServer interface {
	Ping(PLController_PingServer) error
	Traceroute(PLController_TracerouteServer) error
	ReceiveSpoof(*datamodel4.RecSpoof, PLController_ReceiveSpoofServer) error
	GetVPs(*datamodel3.VPRequest, PLController_GetVPsServer) error
	AcceptProbes(context.Context, *datamodel4.SpoofedProbes) (*datamodel4.SpoofedProbesResponse, error)
}

func RegisterPLControllerServer(s *grpc.Server, srv PLControllerServer) {
	s.RegisterService(&_PLController_serviceDesc, srv)
}

func _PLController_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PLControllerServer).Ping(&pLControllerPingServer{stream})
}

type PLController_PingServer interface {
	Send(*datamodel1.Ping) error
	Recv() (*datamodel1.PingArg, error)
	grpc.ServerStream
}

type pLControllerPingServer struct {
	grpc.ServerStream
}

func (x *pLControllerPingServer) Send(m *datamodel1.Ping) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pLControllerPingServer) Recv() (*datamodel1.PingArg, error) {
	m := new(datamodel1.PingArg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PLController_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PLControllerServer).Traceroute(&pLControllerTracerouteServer{stream})
}

type PLController_TracerouteServer interface {
	Send(*datamodel2.Traceroute) error
	Recv() (*datamodel2.TracerouteArg, error)
	grpc.ServerStream
}

type pLControllerTracerouteServer struct {
	grpc.ServerStream
}

func (x *pLControllerTracerouteServer) Send(m *datamodel2.Traceroute) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pLControllerTracerouteServer) Recv() (*datamodel2.TracerouteArg, error) {
	m := new(datamodel2.TracerouteArg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PLController_ReceiveSpoof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel4.RecSpoof)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).ReceiveSpoof(m, &pLControllerReceiveSpoofServer{stream})
}

type PLController_ReceiveSpoofServer interface {
	Send(*datamodel4.NotifyRecSpoofResponse) error
	grpc.ServerStream
}

type pLControllerReceiveSpoofServer struct {
	grpc.ServerStream
}

func (x *pLControllerReceiveSpoofServer) Send(m *datamodel4.NotifyRecSpoofResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PLController_GetVPs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(datamodel3.VPRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PLControllerServer).GetVPs(m, &pLControllerGetVPsServer{stream})
}

type PLController_GetVPsServer interface {
	Send(*datamodel3.VPReturn) error
	grpc.ServerStream
}

type pLControllerGetVPsServer struct {
	grpc.ServerStream
}

func (x *pLControllerGetVPsServer) Send(m *datamodel3.VPReturn) error {
	return x.ServerStream.SendMsg(m)
}

func _PLController_AcceptProbes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(datamodel4.SpoofedProbes)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PLControllerServer).AcceptProbes(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _PLController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PLController",
	HandlerType: (*PLControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptProbes",
			Handler:    _PLController_AcceptProbes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _PLController_Ping_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _PLController_Traceroute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveSpoof",
			Handler:       _PLController_ReceiveSpoof_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetVPs",
			Handler:       _PLController_GetVPs_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x96, 0xd2, 0xc3, 0x52, 0x78, 0x61, 0xab, 0x20, 0x39, 0xa9, 0x27, 0x2f, 0x26,
	0xfe, 0x39, 0x88, 0x07, 0x91, 0x5a, 0x44, 0x28, 0xa5, 0x84, 0x54, 0x7b, 0xf0, 0xb6, 0xd9, 0x4e,
	0xe3, 0x42, 0xba, 0xb3, 0xee, 0x4e, 0x0a, 0x7e, 0x54, 0xbf, 0x8d, 0x69, 0x1a, 0x9b, 0xb4, 0x28,
	0x98, 0xe3, 0x3e, 0xcf, 0xfe, 0x7e, 0xbb, 0x33, 0x6c, 0x94, 0x28, 0x7a, 0xcb, 0x62, 0x5f, 0xe2,
	0x32, 0x98, 0x3c, 0xbe, 0x9c, 0x4f, 0x27, 0xd3, 0x20, 0x82, 0x15, 0x58, 0x07, 0xcf, 0x56, 0x48,
	0xb0, 0x98, 0x11, 0x04, 0x26, 0x95, 0xa8, 0xc9, 0x62, 0x9a, 0x82, 0x0d, 0x4c, 0xbc, 0x73, 0x16,
	0x46, 0xf9, 0xc6, 0x22, 0xa1, 0x77, 0xfb, 0x27, 0xd7, 0x5c, 0x90, 0x58, 0xe2, 0x1c, 0xd2, 0xc0,
	0x28, 0x9d, 0x94, 0xe8, 0x7d, 0x43, 0x94, 0xb6, 0x61, 0x29, 0x18, 0x34, 0x14, 0xac, 0x84, 0x26,
	0x91, 0x80, 0x41, 0xa5, 0xa9, 0x54, 0xdc, 0x35, 0x54, 0x58, 0x90, 0xce, 0x20, 0x2e, 0x36, 0xf8,
	0xd5, 0x67, 0x9b, 0xf5, 0xc2, 0xf1, 0x70, 0xbb, 0x17, 0x7e, 0xc9, 0x3a, 0x61, 0x3e, 0x21, 0xe7,
	0xfe, 0x96, 0xf1, 0xd7, 0xc1, 0xc0, 0x26, 0xde, 0xff, 0xbd, 0xec, 0xf4, 0xdf, 0x59, 0xeb, 0xa2,
	0xc5, 0x87, 0x8c, 0x55, 0x4f, 0xf1, 0xa3, 0xda, 0xa5, 0x2a, 0x5e, 0xe3, 0x87, 0x3f, 0x36, 0xa5,
	0x64, 0xc4, 0x7a, 0x11, 0x48, 0x50, 0x2b, 0x98, 0xae, 0xbf, 0xc7, 0xfb, 0xb5, 0xcb, 0x79, 0x51,
	0x84, 0xde, 0x49, 0x2d, 0x9c, 0x20, 0xa9, 0xc5, 0xc7, 0x77, 0x15, 0x41, 0x3e, 0x95, 0x76, 0xb9,
	0x2d, 0x77, 0xdd, 0xb0, 0xee, 0x13, 0xd0, 0x2c, 0x74, 0xfc, 0xa0, 0x06, 0xcc, 0xc2, 0x08, 0xde,
	0x33, 0x70, 0xe4, 0xf5, 0xf7, 0x52, 0xca, 0xac, 0x2e, 0xc0, 0x31, 0xeb, 0x0d, 0xa4, 0x04, 0x43,
	0xa1, 0xc5, 0x18, 0xdc, 0xce, 0x2c, 0xc5, 0x33, 0x30, 0xdf, 0x34, 0xde, 0xf1, 0x6f, 0x4d, 0xf5,
	0x91, 0x87, 0xce, 0x6b, 0xdb, 0xc4, 0x71, 0xb7, 0x58, 0xf4, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x57, 0x49, 0xb0, 0x5d, 0xb4, 0x02, 0x00, 0x00,
}
