// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/lib/datamodel/returnt.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type MRequestStatus int32

const (
	MRequestStatus_SUCCESS MRequestStatus = 0
	MRequestStatus_ERROR   MRequestStatus = 1
)

var MRequestStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}
var MRequestStatus_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x MRequestStatus) String() string {
	return proto.EnumName(MRequestStatus_name, int32(x))
}

type ReturnT struct {
	Status MRequestStatus `protobuf:"varint,1,opt,enum=datamodel.MRequestStatus" json:"Status,omitempty"`
	Dur    int64          `protobuf:"varint,2,opt" json:"Dur,omitempty"`
}

func (m *ReturnT) Reset()         { *m = ReturnT{} }
func (m *ReturnT) String() string { return proto.CompactTextString(m) }
func (*ReturnT) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("datamodel.MRequestStatus", MRequestStatus_name, MRequestStatus_value)
}
