// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/lib/datamodel/service.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ServiceT int32

const (
	ServiceT_PLANET_LAB ServiceT = 0
)

var ServiceT_name = map[int32]string{
	0: "PLANET_LAB",
}
var ServiceT_value = map[string]int32{
	"PLANET_LAB": 0,
}

func (x ServiceT) String() string {
	return proto.EnumName(ServiceT_name, int32(x))
}

func init() {
	proto.RegisterEnum("datamodel.ServiceT", ServiceT_name, ServiceT_value)
}
