// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/lib/datamodel/stats.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Stats struct {
	StartTime  string `protobuf:"bytes,1,opt,name=start_time" json:"start_time,omitempty"`
	UpTime     int64  `protobuf:"varint,2,opt,name=up_time" json:"up_time,omitempty"`
	Requests   int64  `protobuf:"varint,3,opt,name=requests" json:"requests,omitempty"`
	AvgReqTime int64  `protobuf:"varint,4,opt,name=avg_req_time" json:"avg_req_time,omitempty"`
	TotReqTime int64  `protobuf:"varint,5,opt,name=tot_req_time" json:"tot_req_time,omitempty"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}

type StatsArg struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *StatsArg) Reset()         { *m = StatsArg{} }
func (m *StatsArg) String() string { return proto.CompactTextString(m) }
func (*StatsArg) ProtoMessage()    {}

type StatsReturn struct {
	Ret   *ReturnT `protobuf:"bytes,1,opt,name=ret" json:"ret,omitempty"`
	Stats *Stats   `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
}

func (m *StatsReturn) Reset()         { *m = StatsReturn{} }
func (m *StatsReturn) String() string { return proto.CompactTextString(m) }
func (*StatsReturn) ProtoMessage()    {}

func (m *StatsReturn) GetRet() *ReturnT {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *StatsReturn) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
}
