/*
 Copyright (c) 2015, Northeastern University
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Northeastern University nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL Northeastern University BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/lib/datamodel/vantagepoint.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type VantagePoint struct {
	Hostname    string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Ip          string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Sshable     bool   `protobuf:"varint,3,opt,name=sshable" json:"sshable,omitempty"`
	Ts          bool   `protobuf:"varint,4,opt,name=ts" json:"ts,omitempty"`
	RecordRoute bool   `protobuf:"varint,5,opt,name=record_route" json:"record_route,omitempty"`
	Active      bool   `protobuf:"varint,6,opt,name=active" json:"active,omitempty"`
	LastUpdated int64  `protobuf:"varint,7,opt,name=last_updated" json:"last_updated,omitempty"`
	SudoProblem bool   `protobuf:"varint,8,opt,name=sudo_problem" json:"sudo_problem,omitempty"`
	Spoof       bool   `protobuf:"varint,9,opt,name=spoof" json:"spoof,omitempty"`
	Controller  string `protobuf:"bytes,10,opt,name=controller" json:"controller,omitempty"`
	RecSpoof    bool   `protobuf:"varint,11,opt,name=rec_spoof" json:"rec_spoof,omitempty"`
	ScamperUp   bool   `protobuf:"varint,12,opt,name=scamper_up" json:"scamper_up,omitempty"`
}

func (m *VantagePoint) Reset()         { *m = VantagePoint{} }
func (m *VantagePoint) String() string { return proto.CompactTextString(m) }
func (*VantagePoint) ProtoMessage()    {}

type VPRequest struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Ip       int64  `protobuf:"varint,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *VPRequest) Reset()         { *m = VPRequest{} }
func (m *VPRequest) String() string { return proto.CompactTextString(m) }
func (*VPRequest) ProtoMessage()    {}

type VPReturn struct {
	Vps []*VantagePoint `protobuf:"bytes,1,rep,name=vps" json:"vps,omitempty"`
}

func (m *VPReturn) Reset()         { *m = VPReturn{} }
func (m *VPReturn) String() string { return proto.CompactTextString(m) }
func (*VPReturn) ProtoMessage()    {}

func (m *VPReturn) GetVps() []*VantagePoint {
	if m != nil {
		return m.Vps
	}
	return nil
}

func init() {
}
