// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/revtr/pb/revtr.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/revtr/pb/revtr.proto

It has these top-level messages:
	RevtrMeasurement
	RunRevtrReq
	RunRevtrResp
	GetRevtrReq
	GetRevtrResp
	GetSourcesReq
	GetSourcesResp
	Source
	ReverseTraceroute
	RevtrHop
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RevtrHopType int32

const (
	RevtrHopType_DUMMY                                         RevtrHopType = 0
	RevtrHopType_DST_REV_SEGMENT                               RevtrHopType = 1
	RevtrHopType_DST_SYM_REV_SEGMENT                           RevtrHopType = 2
	RevtrHopType_TR_TO_SRC_REV_SEGMENT                         RevtrHopType = 3
	RevtrHopType_RR_REV_SEGMENT                                RevtrHopType = 4
	RevtrHopType_SPOOF_RR_REV_SEGMENT                          RevtrHopType = 5
	RevtrHopType_TS_ADJ_REV_SEGMENT                            RevtrHopType = 6
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT                      RevtrHopType = 7
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO              RevtrHopType = 8
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP RevtrHopType = 9
)

var RevtrHopType_name = map[int32]string{
	0: "DUMMY",
	1: "DST_REV_SEGMENT",
	2: "DST_SYM_REV_SEGMENT",
	3: "TR_TO_SRC_REV_SEGMENT",
	4: "RR_REV_SEGMENT",
	5: "SPOOF_RR_REV_SEGMENT",
	6: "TS_ADJ_REV_SEGMENT",
	7: "SPOOF_TS_ADJ_REV_SEGMENT",
	8: "SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO",
	9: "SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP",
}
var RevtrHopType_value = map[string]int32{
	"DUMMY":                                         0,
	"DST_REV_SEGMENT":                               1,
	"DST_SYM_REV_SEGMENT":                           2,
	"TR_TO_SRC_REV_SEGMENT":                         3,
	"RR_REV_SEGMENT":                                4,
	"SPOOF_RR_REV_SEGMENT":                          5,
	"TS_ADJ_REV_SEGMENT":                            6,
	"SPOOF_TS_ADJ_REV_SEGMENT":                      7,
	"SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO":              8,
	"SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP": 9,
}

func (x RevtrHopType) String() string {
	return proto.EnumName(RevtrHopType_name, int32(x))
}
func (RevtrHopType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RevtrStatus int32

const (
	RevtrStatus_DUMMY_X   RevtrStatus = 0
	RevtrStatus_RUNNING   RevtrStatus = 1
	RevtrStatus_COMPLETED RevtrStatus = 2
)

var RevtrStatus_name = map[int32]string{
	0: "DUMMY_X",
	1: "RUNNING",
	2: "COMPLETED",
}
var RevtrStatus_value = map[string]int32{
	"DUMMY_X":   0,
	"RUNNING":   1,
	"COMPLETED": 2,
}

func (x RevtrStatus) String() string {
	return proto.EnumName(RevtrStatus_name, int32(x))
}
func (RevtrStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RevtrMeasurement struct {
	Src            string `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Dst            string `protobuf:"bytes,2,opt,name=dst" json:"dst,omitempty"`
	Staleness      uint32 `protobuf:"varint,3,opt,name=staleness" json:"staleness,omitempty"`
	Id             uint32 `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	BackoffEndhost bool   `protobuf:"varint,5,opt,name=backoff_endhost" json:"backoff_endhost,omitempty"`
}

func (m *RevtrMeasurement) Reset()                    { *m = RevtrMeasurement{} }
func (m *RevtrMeasurement) String() string            { return proto.CompactTextString(m) }
func (*RevtrMeasurement) ProtoMessage()               {}
func (*RevtrMeasurement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RunRevtrReq struct {
	Revtrs []*RevtrMeasurement `protobuf:"bytes,1,rep,name=revtrs" json:"revtrs,omitempty"`
}

func (m *RunRevtrReq) Reset()                    { *m = RunRevtrReq{} }
func (m *RunRevtrReq) String() string            { return proto.CompactTextString(m) }
func (*RunRevtrReq) ProtoMessage()               {}
func (*RunRevtrReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RunRevtrReq) GetRevtrs() []*RevtrMeasurement {
	if m != nil {
		return m.Revtrs
	}
	return nil
}

type RunRevtrResp struct {
	BatchId   uint32 `protobuf:"varint,1,opt,name=batch_id" json:"batch_id,omitempty"`
	ResultUrl string `protobuf:"bytes,2,opt,name=result_url" json:"result_url,omitempty"`
}

func (m *RunRevtrResp) Reset()                    { *m = RunRevtrResp{} }
func (m *RunRevtrResp) String() string            { return proto.CompactTextString(m) }
func (*RunRevtrResp) ProtoMessage()               {}
func (*RunRevtrResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetRevtrReq struct {
	BatchId uint32 `protobuf:"varint,1,opt,name=batch_id" json:"batch_id,omitempty"`
}

func (m *GetRevtrReq) Reset()                    { *m = GetRevtrReq{} }
func (m *GetRevtrReq) String() string            { return proto.CompactTextString(m) }
func (*GetRevtrReq) ProtoMessage()               {}
func (*GetRevtrReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetRevtrResp struct {
	Revtrs []*ReverseTraceroute `protobuf:"bytes,1,rep,name=revtrs" json:"revtrs,omitempty"`
}

func (m *GetRevtrResp) Reset()                    { *m = GetRevtrResp{} }
func (m *GetRevtrResp) String() string            { return proto.CompactTextString(m) }
func (*GetRevtrResp) ProtoMessage()               {}
func (*GetRevtrResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRevtrResp) GetRevtrs() []*ReverseTraceroute {
	if m != nil {
		return m.Revtrs
	}
	return nil
}

type GetSourcesReq struct {
}

func (m *GetSourcesReq) Reset()                    { *m = GetSourcesReq{} }
func (m *GetSourcesReq) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesReq) ProtoMessage()               {}
func (*GetSourcesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetSourcesResp struct {
	Srcs []*Source `protobuf:"bytes,1,rep,name=srcs" json:"srcs,omitempty"`
}

func (m *GetSourcesResp) Reset()                    { *m = GetSourcesResp{} }
func (m *GetSourcesResp) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesResp) ProtoMessage()               {}
func (*GetSourcesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetSourcesResp) GetSrcs() []*Source {
	if m != nil {
		return m.Srcs
	}
	return nil
}

type Source struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ReverseTraceroute struct {
	Status     RevtrStatus `protobuf:"varint,1,opt,name=status,enum=pb.RevtrStatus" json:"status,omitempty"`
	Src        string      `protobuf:"bytes,2,opt,name=src" json:"src,omitempty"`
	Dst        string      `protobuf:"bytes,3,opt,name=dst" json:"dst,omitempty"`
	Runtime    int64       `protobuf:"varint,4,opt,name=runtime" json:"runtime,omitempty"`
	RrIssued   int32       `protobuf:"varint,5,opt,name=rr_issued" json:"rr_issued,omitempty"`
	TsIssued   int32       `protobuf:"varint,6,opt,name=ts_issued" json:"ts_issued,omitempty"`
	StopReason string      `protobuf:"bytes,7,opt,name=stop_reason" json:"stop_reason,omitempty"`
	Date       string      `protobuf:"bytes,8,opt,name=date" json:"date,omitempty"`
	Path       []*RevtrHop `protobuf:"bytes,9,rep,name=path" json:"path,omitempty"`
	Id         uint32      `protobuf:"varint,10,opt,name=id" json:"id,omitempty"`
}

func (m *ReverseTraceroute) Reset()                    { *m = ReverseTraceroute{} }
func (m *ReverseTraceroute) String() string            { return proto.CompactTextString(m) }
func (*ReverseTraceroute) ProtoMessage()               {}
func (*ReverseTraceroute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReverseTraceroute) GetPath() []*RevtrHop {
	if m != nil {
		return m.Path
	}
	return nil
}

type RevtrHop struct {
	Hop  string       `protobuf:"bytes,1,opt,name=hop" json:"hop,omitempty"`
	Type RevtrHopType `protobuf:"varint,2,opt,name=type,enum=pb.RevtrHopType" json:"type,omitempty"`
}

func (m *RevtrHop) Reset()                    { *m = RevtrHop{} }
func (m *RevtrHop) String() string            { return proto.CompactTextString(m) }
func (*RevtrHop) ProtoMessage()               {}
func (*RevtrHop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*RevtrMeasurement)(nil), "pb.RevtrMeasurement")
	proto.RegisterType((*RunRevtrReq)(nil), "pb.RunRevtrReq")
	proto.RegisterType((*RunRevtrResp)(nil), "pb.RunRevtrResp")
	proto.RegisterType((*GetRevtrReq)(nil), "pb.GetRevtrReq")
	proto.RegisterType((*GetRevtrResp)(nil), "pb.GetRevtrResp")
	proto.RegisterType((*GetSourcesReq)(nil), "pb.GetSourcesReq")
	proto.RegisterType((*GetSourcesResp)(nil), "pb.GetSourcesResp")
	proto.RegisterType((*Source)(nil), "pb.Source")
	proto.RegisterType((*ReverseTraceroute)(nil), "pb.ReverseTraceroute")
	proto.RegisterType((*RevtrHop)(nil), "pb.RevtrHop")
	proto.RegisterEnum("pb.RevtrHopType", RevtrHopType_name, RevtrHopType_value)
	proto.RegisterEnum("pb.RevtrStatus", RevtrStatus_name, RevtrStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Revtr service

type RevtrClient interface {
	RunRevtr(ctx context.Context, in *RunRevtrReq, opts ...grpc.CallOption) (*RunRevtrResp, error)
	GetRevtr(ctx context.Context, in *GetRevtrReq, opts ...grpc.CallOption) (*GetRevtrResp, error)
	GetSources(ctx context.Context, in *GetSourcesReq, opts ...grpc.CallOption) (*GetSourcesResp, error)
}

type revtrClient struct {
	cc *grpc.ClientConn
}

func NewRevtrClient(cc *grpc.ClientConn) RevtrClient {
	return &revtrClient{cc}
}

func (c *revtrClient) RunRevtr(ctx context.Context, in *RunRevtrReq, opts ...grpc.CallOption) (*RunRevtrResp, error) {
	out := new(RunRevtrResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/RunRevtr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revtrClient) GetRevtr(ctx context.Context, in *GetRevtrReq, opts ...grpc.CallOption) (*GetRevtrResp, error) {
	out := new(GetRevtrResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/GetRevtr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revtrClient) GetSources(ctx context.Context, in *GetSourcesReq, opts ...grpc.CallOption) (*GetSourcesResp, error) {
	out := new(GetSourcesResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/GetSources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Revtr service

type RevtrServer interface {
	RunRevtr(context.Context, *RunRevtrReq) (*RunRevtrResp, error)
	GetRevtr(context.Context, *GetRevtrReq) (*GetRevtrResp, error)
	GetSources(context.Context, *GetSourcesReq) (*GetSourcesResp, error)
}

func RegisterRevtrServer(s *grpc.Server, srv RevtrServer) {
	s.RegisterService(&_Revtr_serviceDesc, srv)
}

func _Revtr_RunRevtr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RunRevtrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RevtrServer).RunRevtr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Revtr_GetRevtr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetRevtrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RevtrServer).GetRevtr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Revtr_GetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetSourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RevtrServer).GetSources(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Revtr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Revtr",
	HandlerType: (*RevtrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunRevtr",
			Handler:    _Revtr_RunRevtr_Handler,
		},
		{
			MethodName: "GetRevtr",
			Handler:    _Revtr_GetRevtr_Handler,
		},
		{
			MethodName: "GetSources",
			Handler:    _Revtr_GetSources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x5d, 0xcb, 0xf7, 0xf1, 0x4d, 0x66, 0x92, 0x8d, 0xd6, 0x08, 0x36, 0x81, 0xb0, 0xbb, 0x08,
	0x0c, 0xc4, 0xc6, 0x3a, 0xbd, 0xa0, 0x7d, 0x4b, 0x62, 0xd5, 0x6d, 0x11, 0xdb, 0x81, 0x24, 0x17,
	0x4d, 0x5e, 0x04, 0xd9, 0x66, 0x62, 0xa3, 0x8e, 0xa8, 0x92, 0x54, 0x80, 0xa2, 0xe8, 0x4b, 0x7f,
	0xa1, 0x1f, 0xd0, 0x5f, 0x2a, 0xd0, 0x5f, 0xe8, 0x7b, 0x7f, 0xa1, 0x14, 0xe5, 0x9b, 0x9c, 0x16,
	0x7d, 0x13, 0xcf, 0x70, 0xce, 0x1c, 0x9d, 0x99, 0x21, 0x3c, 0xb9, 0x99, 0xf2, 0x49, 0x30, 0x6c,
	0x8c, 0xc8, 0x6d, 0xb3, 0x67, 0x0c, 0x8e, 0xac, 0x9e, 0xd5, 0x34, 0xf1, 0x1d, 0xa6, 0x0c, 0xdb,
	0xd4, 0x1d, 0x61, 0x4a, 0x02, 0x8e, 0x9b, 0x14, 0xdf, 0x71, 0xda, 0xf4, 0x87, 0xd1, 0x47, 0xc3,
	0xa7, 0x84, 0x13, 0xa4, 0xf8, 0xc3, 0xda, 0xde, 0x0d, 0x21, 0x37, 0x33, 0xdc, 0x74, 0xfd, 0x69,
	0xd3, 0xf5, 0x3c, 0xc2, 0x5d, 0x3e, 0x25, 0x1e, 0x8b, 0x6e, 0xe8, 0x63, 0x50, 0xcd, 0x30, 0xa1,
	0x8b, 0x5d, 0x16, 0x50, 0x7c, 0x8b, 0x3d, 0x8e, 0x0a, 0x90, 0x64, 0x74, 0xa4, 0x25, 0x0e, 0x12,
	0x87, 0xf9, 0xf0, 0x30, 0x66, 0x5c, 0x53, 0xe4, 0xa1, 0x0a, 0x79, 0xc6, 0xdd, 0x19, 0xf6, 0x30,
	0x63, 0x5a, 0x52, 0x40, 0x25, 0x04, 0xa0, 0x4c, 0xc7, 0x5a, 0x4a, 0x7e, 0xef, 0x42, 0x65, 0xe8,
	0x8e, 0xde, 0x90, 0xeb, 0x6b, 0x07, 0x7b, 0xe3, 0x09, 0x11, 0x79, 0x69, 0x11, 0xc8, 0xe9, 0xc7,
	0x50, 0x30, 0x03, 0x4f, 0x16, 0x32, 0xf1, 0x5b, 0xf4, 0x0f, 0x64, 0xa4, 0x4a, 0x26, 0x6a, 0x24,
	0x0f, 0x0b, 0xad, 0xed, 0x86, 0x3f, 0x6c, 0x6c, 0xca, 0xd0, 0x1f, 0x40, 0x71, 0x95, 0xc4, 0x7c,
	0xa4, 0x42, 0x6e, 0xe8, 0xf2, 0xd1, 0xc4, 0x11, 0xf5, 0x12, 0xb2, 0x9e, 0x28, 0x4e, 0x31, 0x0b,
	0x66, 0xdc, 0x09, 0xe8, 0x2c, 0x92, 0xa8, 0xef, 0x43, 0xa1, 0x83, 0xf9, 0xb2, 0xd4, 0xbd, 0x24,
	0xfd, 0x21, 0x14, 0x57, 0x17, 0x04, 0xed, 0xbf, 0x1b, 0x62, 0x76, 0xe6, 0x62, 0xe2, 0xfe, 0xea,
	0x15, 0x28, 0x89, 0x34, 0x8b, 0x04, 0x74, 0x84, 0x99, 0x60, 0xd6, 0xeb, 0x50, 0x5e, 0x07, 0x04,
	0x93, 0x06, 0x29, 0xe1, 0xdb, 0x82, 0x07, 0x42, 0x9e, 0x28, 0xac, 0xff, 0x07, 0x99, 0xe8, 0x2b,
	0xd4, 0x13, 0xfa, 0xe2, 0xb9, 0xb7, 0x78, 0x6e, 0x70, 0x68, 0xa0, 0x3f, 0x17, 0xff, 0x25, 0x01,
	0xd5, 0x7b, 0xa5, 0xd1, 0x3e, 0x64, 0x84, 0xeb, 0x3c, 0x60, 0x32, 0xa3, 0xdc, 0xaa, 0x2c, 0xed,
	0xb2, 0x24, 0xbc, 0x68, 0x98, 0xb2, 0xde, 0xb0, 0xa4, 0x3c, 0x54, 0x20, 0x4b, 0x03, 0x8f, 0x4f,
	0x45, 0xb5, 0xb0, 0x45, 0xc9, 0xb0, 0x83, 0x94, 0x3a, 0x53, 0xc6, 0x02, 0x3c, 0x96, 0xcd, 0x49,
	0x87, 0x10, 0x67, 0x0b, 0x28, 0x23, 0xa1, 0x2d, 0x28, 0x30, 0x4e, 0x7c, 0x87, 0x8a, 0x76, 0x10,
	0x4f, 0xcb, 0x4a, 0xae, 0x22, 0xa4, 0xc6, 0x2e, 0xc7, 0x5a, 0x4e, 0x9e, 0x6a, 0x90, 0xf2, 0x5d,
	0x3e, 0xd1, 0xf2, 0xf2, 0x67, 0x8b, 0x4b, 0x49, 0xcf, 0x89, 0x3f, 0x9f, 0x09, 0x90, 0x76, 0x3f,
	0x86, 0xdc, 0x12, 0x17, 0xd2, 0x26, 0xc4, 0x9f, 0xff, 0xf7, 0xdf, 0x90, 0xe2, 0xef, 0x7c, 0x2c,
	0x55, 0x97, 0x5b, 0xea, 0x3a, 0x81, 0x2d, 0xf0, 0xfa, 0x67, 0x45, 0xf4, 0x7f, 0x0d, 0x40, 0x79,
	0x48, 0xb7, 0x07, 0xdd, 0xee, 0xa5, 0xfa, 0x87, 0xd0, 0x57, 0x69, 0x5b, 0xb6, 0x63, 0x1a, 0xaf,
	0x1c, 0xcb, 0xe8, 0x74, 0x8d, 0x9e, 0xad, 0x26, 0xc4, 0xf4, 0x6d, 0x85, 0xa0, 0x75, 0xd9, 0x8d,
	0x05, 0x14, 0xf4, 0x17, 0xec, 0xd8, 0xa6, 0x63, 0xf7, 0x1d, 0xcb, 0x3c, 0x8b, 0x85, 0x92, 0x62,
	0x82, 0xca, 0xa6, 0x19, 0xc3, 0x52, 0xa2, 0x8d, 0xdb, 0xd6, 0x45, 0xbf, 0xff, 0xcc, 0xd9, 0x88,
	0xa4, 0xd1, 0x9f, 0x80, 0x6c, 0xcb, 0x39, 0x69, 0xbf, 0x8c, 0xe1, 0x19, 0xb4, 0x07, 0x5a, 0x94,
	0xf1, 0x93, 0x68, 0x56, 0x4c, 0xfb, 0xc1, 0xaf, 0xa2, 0x21, 0x74, 0x65, 0x98, 0x7d, 0x35, 0x87,
	0xfe, 0x87, 0xa3, 0xdf, 0xdd, 0x72, 0xda, 0xfd, 0xc1, 0xe9, 0xb9, 0xe1, 0x58, 0xf6, 0x49, 0xf7,
	0x42, 0xcd, 0xd7, 0x1f, 0x89, 0xad, 0x8a, 0x4d, 0x41, 0x56, 0xfa, 0xe3, 0xbc, 0x16, 0x0e, 0x89,
	0x83, 0x39, 0xe8, 0xf5, 0x5e, 0xf4, 0x3a, 0xc2, 0x99, 0x12, 0xe4, 0xcf, 0xfa, 0xdd, 0x8b, 0x73,
	0xc3, 0x36, 0xda, 0xaa, 0xd2, 0xfa, 0x9e, 0x80, 0xb4, 0x4c, 0x44, 0x1d, 0xd1, 0x9c, 0xf9, 0x8a,
	0xa1, 0x68, 0xaa, 0x56, 0x5b, 0x5a, 0x53, 0xe3, 0x00, 0xf3, 0x75, 0xed, 0xe3, 0xd7, 0x6f, 0x9f,
	0x14, 0xa4, 0x97, 0xe4, 0x63, 0x72, 0xd7, 0x8a, 0xde, 0x9a, 0xa7, 0x89, 0x3a, 0xea, 0x43, 0x6e,
	0xb1, 0x54, 0x11, 0xd1, 0xda, 0x0e, 0x46, 0x44, 0xeb, 0x3b, 0xa7, 0x1f, 0x48, 0xa2, 0x1a, 0xd2,
	0x62, 0x44, 0xcd, 0xf7, 0x8b, 0x55, 0xfd, 0x80, 0xce, 0x01, 0x56, 0xdb, 0x85, 0xaa, 0x73, 0x86,
	0xd5, 0xfa, 0xd5, 0xd0, 0x26, 0x24, 0x68, 0x77, 0x25, 0x6d, 0x15, 0x55, 0x16, 0xb4, 0x2c, 0x0a,
	0x9e, 0xa6, 0xae, 0xc4, 0x4b, 0x38, 0xcc, 0xc8, 0x27, 0xef, 0xf8, 0x47, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0xba, 0x9e, 0xa6, 0x51, 0x05, 0x00, 0x00,
}
