// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/revtr/pb/revtr.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/revtr/pb/revtr.proto

It has these top-level messages:
	RevtrMeasurement
	RunRevtrReq
	RunRevtrResp
	GetRevtrReq
	GetRevtrResp
	GetSourcesReq
	GetSourcesResp
	Source
	ReverseTraceroute
	Stats
	RevtrHop
	RevtrUser
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RevtrHopType int32

const (
	RevtrHopType_DUMMY                                         RevtrHopType = 0
	RevtrHopType_DST_REV_SEGMENT                               RevtrHopType = 1
	RevtrHopType_DST_SYM_REV_SEGMENT                           RevtrHopType = 2
	RevtrHopType_TR_TO_SRC_REV_SEGMENT                         RevtrHopType = 3
	RevtrHopType_RR_REV_SEGMENT                                RevtrHopType = 4
	RevtrHopType_SPOOF_RR_REV_SEGMENT                          RevtrHopType = 5
	RevtrHopType_TS_ADJ_REV_SEGMENT                            RevtrHopType = 6
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT                      RevtrHopType = 7
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO              RevtrHopType = 8
	RevtrHopType_SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP RevtrHopType = 9
)

var RevtrHopType_name = map[int32]string{
	0: "DUMMY",
	1: "DST_REV_SEGMENT",
	2: "DST_SYM_REV_SEGMENT",
	3: "TR_TO_SRC_REV_SEGMENT",
	4: "RR_REV_SEGMENT",
	5: "SPOOF_RR_REV_SEGMENT",
	6: "TS_ADJ_REV_SEGMENT",
	7: "SPOOF_TS_ADJ_REV_SEGMENT",
	8: "SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO",
	9: "SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP",
}
var RevtrHopType_value = map[string]int32{
	"DUMMY":                                         0,
	"DST_REV_SEGMENT":                               1,
	"DST_SYM_REV_SEGMENT":                           2,
	"TR_TO_SRC_REV_SEGMENT":                         3,
	"RR_REV_SEGMENT":                                4,
	"SPOOF_RR_REV_SEGMENT":                          5,
	"TS_ADJ_REV_SEGMENT":                            6,
	"SPOOF_TS_ADJ_REV_SEGMENT":                      7,
	"SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO":              8,
	"SPOOF_TS_ADJ_REV_SEGMENT_TS_ZERO_DOUBLE_STAMP": 9,
}

func (x RevtrHopType) String() string {
	return proto.EnumName(RevtrHopType_name, int32(x))
}
func (RevtrHopType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RevtrStatus int32

const (
	RevtrStatus_DUMMY_X   RevtrStatus = 0
	RevtrStatus_RUNNING   RevtrStatus = 1
	RevtrStatus_COMPLETED RevtrStatus = 2
	RevtrStatus_CANCELED  RevtrStatus = 3
)

var RevtrStatus_name = map[int32]string{
	0: "DUMMY_X",
	1: "RUNNING",
	2: "COMPLETED",
	3: "CANCELED",
}
var RevtrStatus_value = map[string]int32{
	"DUMMY_X":   0,
	"RUNNING":   1,
	"COMPLETED": 2,
	"CANCELED":  3,
}

func (x RevtrStatus) String() string {
	return proto.EnumName(RevtrStatus_name, int32(x))
}
func (RevtrStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RevtrMeasurement struct {
	Src            string `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Dst            string `protobuf:"bytes,2,opt,name=dst" json:"dst,omitempty"`
	Staleness      uint32 `protobuf:"varint,3,opt,name=staleness" json:"staleness,omitempty"`
	Id             uint32 `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	BackoffEndhost bool   `protobuf:"varint,5,opt,name=backoff_endhost" json:"backoff_endhost,omitempty"`
}

func (m *RevtrMeasurement) Reset()                    { *m = RevtrMeasurement{} }
func (m *RevtrMeasurement) String() string            { return proto.CompactTextString(m) }
func (*RevtrMeasurement) ProtoMessage()               {}
func (*RevtrMeasurement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RunRevtrReq struct {
	Revtrs []*RevtrMeasurement `protobuf:"bytes,1,rep,name=revtrs" json:"revtrs,omitempty"`
	Auth   string              `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
}

func (m *RunRevtrReq) Reset()                    { *m = RunRevtrReq{} }
func (m *RunRevtrReq) String() string            { return proto.CompactTextString(m) }
func (*RunRevtrReq) ProtoMessage()               {}
func (*RunRevtrReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RunRevtrReq) GetRevtrs() []*RevtrMeasurement {
	if m != nil {
		return m.Revtrs
	}
	return nil
}

type RunRevtrResp struct {
	BatchId uint32 `protobuf:"varint,1,opt,name=batch_id" json:"batch_id,omitempty"`
}

func (m *RunRevtrResp) Reset()                    { *m = RunRevtrResp{} }
func (m *RunRevtrResp) String() string            { return proto.CompactTextString(m) }
func (*RunRevtrResp) ProtoMessage()               {}
func (*RunRevtrResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetRevtrReq struct {
	BatchId uint32 `protobuf:"varint,1,opt,name=batch_id" json:"batch_id,omitempty"`
	Auth    string `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
}

func (m *GetRevtrReq) Reset()                    { *m = GetRevtrReq{} }
func (m *GetRevtrReq) String() string            { return proto.CompactTextString(m) }
func (*GetRevtrReq) ProtoMessage()               {}
func (*GetRevtrReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetRevtrResp struct {
	Revtrs []*ReverseTraceroute `protobuf:"bytes,1,rep,name=revtrs" json:"revtrs,omitempty"`
}

func (m *GetRevtrResp) Reset()                    { *m = GetRevtrResp{} }
func (m *GetRevtrResp) String() string            { return proto.CompactTextString(m) }
func (*GetRevtrResp) ProtoMessage()               {}
func (*GetRevtrResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRevtrResp) GetRevtrs() []*ReverseTraceroute {
	if m != nil {
		return m.Revtrs
	}
	return nil
}

type GetSourcesReq struct {
	Auth string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
}

func (m *GetSourcesReq) Reset()                    { *m = GetSourcesReq{} }
func (m *GetSourcesReq) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesReq) ProtoMessage()               {}
func (*GetSourcesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetSourcesResp struct {
	Srcs []*Source `protobuf:"bytes,1,rep,name=srcs" json:"srcs,omitempty"`
}

func (m *GetSourcesResp) Reset()                    { *m = GetSourcesResp{} }
func (m *GetSourcesResp) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesResp) ProtoMessage()               {}
func (*GetSourcesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetSourcesResp) GetSrcs() []*Source {
	if m != nil {
		return m.Srcs
	}
	return nil
}

type Source struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Site     string `protobuf:"bytes,3,opt,name=site" json:"site,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ReverseTraceroute struct {
	Status     RevtrStatus `protobuf:"varint,1,opt,name=status,enum=pb.RevtrStatus" json:"status,omitempty"`
	Src        string      `protobuf:"bytes,2,opt,name=src" json:"src,omitempty"`
	Dst        string      `protobuf:"bytes,3,opt,name=dst" json:"dst,omitempty"`
	Runtime    int64       `protobuf:"varint,4,opt,name=runtime" json:"runtime,omitempty"`
	StopReason string      `protobuf:"bytes,5,opt,name=stop_reason" json:"stop_reason,omitempty"`
	Date       string      `protobuf:"bytes,6,opt,name=date" json:"date,omitempty"`
	Path       []*RevtrHop `protobuf:"bytes,7,rep,name=path" json:"path,omitempty"`
	Id         uint32      `protobuf:"varint,8,opt,name=id" json:"id,omitempty"`
	FailReason string      `protobuf:"bytes,9,opt,name=fail_reason" json:"fail_reason,omitempty"`
	Stats      *Stats      `protobuf:"bytes,10,opt,name=stats" json:"stats,omitempty"`
}

func (m *ReverseTraceroute) Reset()                    { *m = ReverseTraceroute{} }
func (m *ReverseTraceroute) String() string            { return proto.CompactTextString(m) }
func (*ReverseTraceroute) ProtoMessage()               {}
func (*ReverseTraceroute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReverseTraceroute) GetPath() []*RevtrHop {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ReverseTraceroute) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Stats struct {
	TsDuration                *google_protobuf1.Duration `protobuf:"bytes,1,opt,name=ts_duration" json:"ts_duration,omitempty"`
	RrDuration                *google_protobuf1.Duration `protobuf:"bytes,2,opt,name=rr_duration" json:"rr_duration,omitempty"`
	TrToSrcDuration           *google_protobuf1.Duration `protobuf:"bytes,3,opt,name=tr_to_src_duration" json:"tr_to_src_duration,omitempty"`
	AssumeSymmetricDuration   *google_protobuf1.Duration `protobuf:"bytes,4,opt,name=assume_symmetric_duration" json:"assume_symmetric_duration,omitempty"`
	BackgroundTrsDuration     *google_protobuf1.Duration `protobuf:"bytes,5,opt,name=background_trs_duration" json:"background_trs_duration,omitempty"`
	RrProbes                  int32                      `protobuf:"varint,6,opt,name=rr_probes" json:"rr_probes,omitempty"`
	SpoofedRrProbes           int32                      `protobuf:"varint,7,opt,name=spoofed_rr_probes" json:"spoofed_rr_probes,omitempty"`
	TsProbes                  int32                      `protobuf:"varint,8,opt,name=ts_probes" json:"ts_probes,omitempty"`
	SpoofedTsProbes           int32                      `protobuf:"varint,9,opt,name=spoofed_ts_probes" json:"spoofed_ts_probes,omitempty"`
	RrRoundCount              int32                      `protobuf:"varint,10,opt,name=rr_round_count" json:"rr_round_count,omitempty"`
	TsRoundCount              int32                      `protobuf:"varint,11,opt,name=ts_round_count" json:"ts_round_count,omitempty"`
	TrToSrcRoundCount         int32                      `protobuf:"varint,12,opt,name=tr_to_src_round_count" json:"tr_to_src_round_count,omitempty"`
	AssumeSymmetricRoundCount int32                      `protobuf:"varint,13,opt,name=assume_symmetric_round_count" json:"assume_symmetric_round_count,omitempty"`
	BackgroundTrsRoundCount   int32                      `protobuf:"varint,14,opt,name=background_trs_round_count" json:"background_trs_round_count,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Stats) GetTsDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.TsDuration
	}
	return nil
}

func (m *Stats) GetRrDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.RrDuration
	}
	return nil
}

func (m *Stats) GetTrToSrcDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.TrToSrcDuration
	}
	return nil
}

func (m *Stats) GetAssumeSymmetricDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.AssumeSymmetricDuration
	}
	return nil
}

func (m *Stats) GetBackgroundTrsDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.BackgroundTrsDuration
	}
	return nil
}

type RevtrHop struct {
	Hop  string       `protobuf:"bytes,1,opt,name=hop" json:"hop,omitempty"`
	Type RevtrHopType `protobuf:"varint,2,opt,name=type,enum=pb.RevtrHopType" json:"type,omitempty"`
}

func (m *RevtrHop) Reset()                    { *m = RevtrHop{} }
func (m *RevtrHop) String() string            { return proto.CompactTextString(m) }
func (*RevtrHop) ProtoMessage()               {}
func (*RevtrHop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RevtrUser struct {
	Id    uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Max   uint32 `protobuf:"varint,4,opt,name=max" json:"max,omitempty"`
	Delay uint32 `protobuf:"varint,5,opt,name=delay" json:"delay,omitempty"`
	Key   string `protobuf:"bytes,6,opt,name=key" json:"key,omitempty"`
}

func (m *RevtrUser) Reset()                    { *m = RevtrUser{} }
func (m *RevtrUser) String() string            { return proto.CompactTextString(m) }
func (*RevtrUser) ProtoMessage()               {}
func (*RevtrUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*RevtrMeasurement)(nil), "pb.RevtrMeasurement")
	proto.RegisterType((*RunRevtrReq)(nil), "pb.RunRevtrReq")
	proto.RegisterType((*RunRevtrResp)(nil), "pb.RunRevtrResp")
	proto.RegisterType((*GetRevtrReq)(nil), "pb.GetRevtrReq")
	proto.RegisterType((*GetRevtrResp)(nil), "pb.GetRevtrResp")
	proto.RegisterType((*GetSourcesReq)(nil), "pb.GetSourcesReq")
	proto.RegisterType((*GetSourcesResp)(nil), "pb.GetSourcesResp")
	proto.RegisterType((*Source)(nil), "pb.Source")
	proto.RegisterType((*ReverseTraceroute)(nil), "pb.ReverseTraceroute")
	proto.RegisterType((*Stats)(nil), "pb.Stats")
	proto.RegisterType((*RevtrHop)(nil), "pb.RevtrHop")
	proto.RegisterType((*RevtrUser)(nil), "pb.RevtrUser")
	proto.RegisterEnum("pb.RevtrHopType", RevtrHopType_name, RevtrHopType_value)
	proto.RegisterEnum("pb.RevtrStatus", RevtrStatus_name, RevtrStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Revtr service

type RevtrClient interface {
	RunRevtr(ctx context.Context, in *RunRevtrReq, opts ...grpc.CallOption) (*RunRevtrResp, error)
	GetRevtr(ctx context.Context, in *GetRevtrReq, opts ...grpc.CallOption) (*GetRevtrResp, error)
	GetSources(ctx context.Context, in *GetSourcesReq, opts ...grpc.CallOption) (*GetSourcesResp, error)
}

type revtrClient struct {
	cc *grpc.ClientConn
}

func NewRevtrClient(cc *grpc.ClientConn) RevtrClient {
	return &revtrClient{cc}
}

func (c *revtrClient) RunRevtr(ctx context.Context, in *RunRevtrReq, opts ...grpc.CallOption) (*RunRevtrResp, error) {
	out := new(RunRevtrResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/RunRevtr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revtrClient) GetRevtr(ctx context.Context, in *GetRevtrReq, opts ...grpc.CallOption) (*GetRevtrResp, error) {
	out := new(GetRevtrResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/GetRevtr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revtrClient) GetSources(ctx context.Context, in *GetSourcesReq, opts ...grpc.CallOption) (*GetSourcesResp, error) {
	out := new(GetSourcesResp)
	err := grpc.Invoke(ctx, "/pb.Revtr/GetSources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Revtr service

type RevtrServer interface {
	RunRevtr(context.Context, *RunRevtrReq) (*RunRevtrResp, error)
	GetRevtr(context.Context, *GetRevtrReq) (*GetRevtrResp, error)
	GetSources(context.Context, *GetSourcesReq) (*GetSourcesResp, error)
}

func RegisterRevtrServer(s *grpc.Server, srv RevtrServer) {
	s.RegisterService(&_Revtr_serviceDesc, srv)
}

func _Revtr_RunRevtr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRevtrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevtrServer).RunRevtr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Revtr/RunRevtr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevtrServer).RunRevtr(ctx, req.(*RunRevtrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Revtr_GetRevtr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevtrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevtrServer).GetRevtr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Revtr/GetRevtr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevtrServer).GetRevtr(ctx, req.(*GetRevtrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Revtr_GetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevtrServer).GetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Revtr/GetSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevtrServer).GetSources(ctx, req.(*GetSourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Revtr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Revtr",
	HandlerType: (*RevtrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunRevtr",
			Handler:    _Revtr_RunRevtr_Handler,
		},
		{
			MethodName: "GetRevtr",
			Handler:    _Revtr_GetRevtr_Handler,
		},
		{
			MethodName: "GetSources",
			Handler:    _Revtr_GetSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/NEU-SNS/ReverseTraceroute/revtr/pb/revtr.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1003 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x55, 0x4f, 0x6f, 0xe3, 0x54,
	0x10, 0x27, 0x7f, 0x1b, 0x4f, 0xfe, 0xbf, 0xdd, 0x52, 0x37, 0xea, 0x2e, 0x95, 0xb5, 0x48, 0xab,
	0x4a, 0x4d, 0x44, 0x60, 0x85, 0x58, 0x71, 0xe9, 0x36, 0xa1, 0x80, 0x9a, 0xa4, 0xb2, 0x13, 0xc4,
	0xae, 0x84, 0x2c, 0x27, 0x79, 0x69, 0xa2, 0x6d, 0x6c, 0xe3, 0xf7, 0x5c, 0x51, 0x21, 0x2e, 0xdc,
	0x39, 0xf1, 0x01, 0xf8, 0x50, 0x9c, 0xb8, 0x73, 0xe7, 0x2b, 0x30, 0x1e, 0xdb, 0xb1, 0x93, 0x82,
	0x72, 0x89, 0xf2, 0xe6, 0x37, 0xf3, 0x9b, 0xf1, 0x6f, 0xe6, 0xcd, 0x83, 0x2f, 0x6e, 0x57, 0x72,
	0xe9, 0x4f, 0xdb, 0x33, 0x67, 0xdd, 0x19, 0xf6, 0x27, 0xe7, 0xc6, 0xd0, 0xe8, 0xe8, 0xfc, 0x9e,
	0x7b, 0x82, 0x8f, 0x3d, 0x6b, 0xc6, 0x3d, 0xc7, 0x97, 0xbc, 0xe3, 0xf1, 0x7b, 0xe9, 0x75, 0xdc,
	0x69, 0xf8, 0xa7, 0xed, 0x7a, 0x8e, 0x74, 0x58, 0xd6, 0x9d, 0xb6, 0x4e, 0x6e, 0x1d, 0xe7, 0xf6,
	0x8e, 0x77, 0x2c, 0x77, 0xd5, 0xb1, 0x6c, 0xdb, 0x91, 0x96, 0x5c, 0x39, 0xb6, 0x08, 0x3d, 0x5a,
	0xcf, 0x23, 0x94, 0x4e, 0x53, 0x7f, 0xd1, 0x99, 0xfb, 0x1e, 0x39, 0x84, 0xb8, 0x36, 0x87, 0x86,
	0x1e, 0x10, 0x0e, 0xb8, 0x25, 0x7c, 0x8f, 0xaf, 0xb9, 0x2d, 0x59, 0x19, 0x72, 0xc2, 0x9b, 0xa9,
	0x99, 0xd3, 0xcc, 0x4b, 0x25, 0x38, 0xcc, 0x85, 0x54, 0xb3, 0x74, 0x68, 0x82, 0x22, 0xa4, 0x75,
	0xc7, 0x6d, 0x2e, 0x84, 0x9a, 0x43, 0x53, 0x95, 0x01, 0x64, 0x57, 0x73, 0x35, 0x4f, 0xff, 0x8f,
	0xa0, 0x3e, 0xb5, 0x66, 0xef, 0x9d, 0xc5, 0xc2, 0xe4, 0xf6, 0x7c, 0xe9, 0x60, 0x5c, 0x01, 0x81,
	0x92, 0x76, 0x01, 0x65, 0xdd, 0xb7, 0x29, 0x91, 0xce, 0x7f, 0x64, 0x2f, 0xa0, 0x48, 0x5f, 0x21,
	0x30, 0x47, 0xee, 0x65, 0xb9, 0xfb, 0xb4, 0xed, 0x4e, 0xdb, 0x8f, 0xca, 0xa8, 0x40, 0xde, 0xf2,
	0xe5, 0x32, 0x4c, 0xad, 0x9d, 0x42, 0x25, 0xa1, 0x10, 0x2e, 0x6b, 0x40, 0x69, 0x6a, 0xc9, 0xd9,
	0xd2, 0xc4, 0xec, 0x41, 0xa5, 0x55, 0xed, 0x1c, 0xca, 0x57, 0x5c, 0x6e, 0x92, 0x3c, 0x72, 0xd8,
	0x21, 0x7c, 0x05, 0x95, 0xc4, 0x1d, 0x09, 0x3f, 0xde, 0x29, 0xea, 0x30, 0x2a, 0x6a, 0xbb, 0x0f,
	0xda, 0x33, 0xa8, 0x62, 0x98, 0xe1, 0xf8, 0xde, 0x8c, 0x8b, 0x20, 0x4f, 0xcc, 0x4a, 0x72, 0x69,
	0x67, 0x50, 0x4b, 0xc3, 0xc8, 0xab, 0x42, 0x1e, 0xd5, 0x8c, 0x59, 0x21, 0x60, 0x0d, 0x61, 0xed,
	0x33, 0x28, 0x86, 0xff, 0x82, 0x5a, 0x03, 0xb5, 0x6c, 0x6b, 0xcd, 0x23, 0xd9, 0x03, 0x59, 0xdd,
	0x48, 0x75, 0xcc, 0x20, 0x56, 0x92, 0x93, 0xe0, 0x8a, 0xf6, 0x57, 0x06, 0x9a, 0x8f, 0xca, 0x62,
	0x1f, 0x41, 0x11, 0x3b, 0x23, 0x7d, 0x41, 0xf1, 0xb5, 0x6e, 0x7d, 0x23, 0xa9, 0x41, 0xe6, 0xb8,
	0xa9, 0xd9, 0x74, 0x53, 0x89, 0x90, 0xd5, 0xe1, 0xc0, 0xf3, 0x6d, 0xb9, 0xc2, 0xdc, 0x41, 0x1b,
	0x73, 0xec, 0x09, 0x94, 0x85, 0x74, 0x5c, 0xd3, 0xc3, 0x66, 0x38, 0x36, 0xb5, 0x90, 0x8a, 0x98,
	0x5b, 0x58, 0x44, 0x91, 0x4e, 0x2d, 0xc8, 0xbb, 0x16, 0x7e, 0xf4, 0x01, 0x7d, 0x54, 0x65, 0x93,
	0xec, 0x6b, 0xc7, 0x8d, 0x26, 0xa2, 0x44, 0x92, 0x23, 0xd5, 0xc2, 0x5a, 0xdd, 0xc5, 0x54, 0x0a,
	0x05, 0xab, 0x50, 0x08, 0x6a, 0x15, 0x2a, 0xe0, 0xb1, 0xdc, 0x55, 0x48, 0x92, 0xc0, 0xa0, 0xfd,
	0x96, 0x87, 0x02, 0xfd, 0x63, 0x6d, 0x28, 0x4b, 0x61, 0xc6, 0xc3, 0x4a, 0x1f, 0x55, 0xee, 0x1e,
	0xb7, 0xc3, 0x69, 0x6e, 0xc7, 0xd3, 0xdc, 0xee, 0x45, 0x0e, 0x81, 0xbf, 0xe7, 0x25, 0xfe, 0xd9,
	0x7d, 0xfe, 0xaf, 0x80, 0x49, 0xcf, 0x94, 0x8e, 0x89, 0xa2, 0x24, 0x61, 0xb9, 0x7d, 0x61, 0x5f,
	0xc2, 0xb1, 0x25, 0x84, 0xbf, 0xe6, 0xa6, 0x78, 0x58, 0xaf, 0xb9, 0xf4, 0x56, 0xa9, 0xe8, 0xfc,
	0xbe, 0xe8, 0xd7, 0x70, 0x14, 0xdc, 0x8f, 0x5b, 0x6c, 0x99, 0x3d, 0x37, 0x71, 0xd4, 0x92, 0xd8,
	0xc2, 0xbe, 0x58, 0xbc, 0x7a, 0xf8, 0x81, 0x68, 0x9f, 0x72, 0x41, 0x4d, 0x28, 0xb0, 0x63, 0x68,
	0x0a, 0xd7, 0x71, 0x16, 0x7c, 0x6e, 0x26, 0xd0, 0x01, 0x41, 0xe8, 0x8d, 0xf2, 0x45, 0xa6, 0xd2,
	0xae, 0x77, 0x02, 0x29, 0x04, 0x7d, 0x08, 0x35, 0x24, 0x08, 0xab, 0x9a, 0xe1, 0xaf, 0xa4, 0xce,
	0x90, 0x1d, 0x5d, 0xd3, 0xf6, 0x32, 0xd9, 0x9f, 0xc1, 0x61, 0x22, 0x5e, 0x1a, 0xae, 0x10, 0xfc,
	0x02, 0x4e, 0x1e, 0x89, 0x94, 0xf6, 0xaa, 0x92, 0x97, 0x06, 0xad, 0x1d, 0x31, 0xd2, 0x3e, 0xb5,
	0xc0, 0x47, 0xfb, 0x1c, 0x4a, 0x9b, 0xb1, 0xc2, 0x99, 0x5d, 0x3a, 0x6e, 0x74, 0x3d, 0x9e, 0x43,
	0x5e, 0x3e, 0xb8, 0x9c, 0xfa, 0x5c, 0xeb, 0x36, 0xd2, 0xf3, 0x37, 0x46, 0xbb, 0xf6, 0x03, 0x28,
	0x74, 0x9e, 0x08, 0xee, 0x45, 0x03, 0xb9, 0xd9, 0x01, 0x74, 0xcb, 0xc2, 0x7b, 0x50, 0x85, 0x02,
	0x5f, 0xe3, 0x7c, 0x46, 0x37, 0x01, 0x53, 0xac, 0xad, 0x9f, 0xa2, 0x65, 0x86, 0xd8, 0x9c, 0xdf,
	0x59, 0x0f, 0xd4, 0x9a, 0x6a, 0x80, 0xbd, 0xe7, 0x0f, 0xe1, 0xf8, 0x9f, 0xfd, 0x91, 0xc5, 0x6d,
	0x94, 0xca, 0xc7, 0x14, 0x28, 0xf4, 0x26, 0x83, 0xc1, 0xdb, 0xc6, 0x07, 0x38, 0xf2, 0xf5, 0x9e,
	0x31, 0x36, 0xf5, 0xfe, 0x77, 0xa6, 0xd1, 0xbf, 0x1a, 0xf4, 0x87, 0xe3, 0x46, 0x06, 0x37, 0xe3,
	0x93, 0xc0, 0x68, 0xbc, 0x1d, 0x6c, 0x01, 0x59, 0xec, 0xca, 0xe1, 0x58, 0x37, 0xc7, 0x23, 0xd3,
	0xd0, 0x2f, 0xb7, 0xa0, 0x1c, 0x63, 0x50, 0xd3, 0xf5, 0x2d, 0x5b, 0x1e, 0xaf, 0xce, 0x53, 0xe3,
	0x66, 0x34, 0xfa, 0xca, 0xdc, 0x41, 0x82, 0x5e, 0xb1, 0xb1, 0x61, 0x5e, 0xf4, 0xbe, 0xdd, 0xb2,
	0x17, 0xd9, 0x09, 0xa8, 0x61, 0xc4, 0x7f, 0xa0, 0x07, 0xd8, 0xaa, 0xd3, 0xff, 0x43, 0x03, 0xd3,
	0xbb, 0xbe, 0x3e, 0x6a, 0x94, 0xd8, 0x27, 0x70, 0xbe, 0xcf, 0xcb, 0xec, 0x8d, 0x26, 0x6f, 0xae,
	0xfb, 0xa6, 0x31, 0xbe, 0x18, 0xdc, 0x34, 0x94, 0xb3, 0x1e, 0x6e, 0xfc, 0xad, 0xed, 0x73, 0x40,
	0xfa, 0x98, 0xdf, 0xa3, 0x42, 0x78, 0xd0, 0x27, 0xc3, 0xe1, 0x37, 0xc3, 0x2b, 0x54, 0xa6, 0x0a,
	0xca, 0xe5, 0x68, 0x70, 0x73, 0xdd, 0x1f, 0xf7, 0x7b, 0xa8, 0x47, 0x05, 0x4a, 0x97, 0x17, 0xc3,
	0xcb, 0xfe, 0x35, 0x9e, 0x72, 0xdd, 0x7f, 0x32, 0x50, 0x20, 0x1a, 0x76, 0x85, 0x93, 0x10, 0xad,
	0x7f, 0x16, 0xee, 0xb6, 0xe4, 0x3d, 0x69, 0x35, 0xb6, 0x0d, 0xc2, 0xd5, 0xd4, 0x5f, 0xff, 0xfc,
	0xfb, 0xf7, 0x2c, 0xd3, 0xaa, 0xf4, 0x2c, 0xde, 0x77, 0xc3, 0x57, 0xf3, 0x75, 0xe6, 0x8c, 0x8d,
	0xa0, 0x14, 0xaf, 0xfd, 0x90, 0x28, 0xf5, 0x66, 0x84, 0x44, 0xe9, 0x57, 0x41, 0x3b, 0x25, 0xa2,
	0x16, 0x53, 0xb7, 0x88, 0x3a, 0x3f, 0xc7, 0x4f, 0xcb, 0x2f, 0xec, 0x1a, 0x20, 0xd9, 0xf8, 0xac,
	0x19, 0x31, 0x24, 0x0f, 0x44, 0x8b, 0xed, 0x9a, 0x90, 0xf6, 0x88, 0x68, 0x9b, 0xac, 0x1e, 0xd3,
	0x8a, 0x10, 0x7c, 0x93, 0x7f, 0x87, 0x6f, 0xfa, 0xb4, 0x48, 0xf7, 0xff, 0xd3, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x82, 0xb3, 0x2e, 0x1b, 0x08, 0x00, 0x00,
}
