// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/intersectrequest.proto
// DO NOT EDIT!

/*
Package datamodel is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/datamodel/intersectrequest.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/ping.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/recspoof.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/reverse_traceroute.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/service.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/time.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/traceroute.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/update.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/vantagepoint.proto

It has these top-level messages:
	Hop
	Path
	IntersectionRequest
	IntersectionResponse
	TokenRequest
	TokenResponse
	PingMeasurement
	PingArg
	PingStats
	PingResponse
	TsAndAddr
	Ping
	RecSpoof
	Spoof
	SpoofedProbes
	SpoofedProbesResponse
	Probe
	RecordRoute
	TimeStamp
	Stamp
	NotifyRecSpoofResponse
	ReceiveSpoofedProbesResponse
	RevtrMeasurement
	RevtrRequest
	ReverseTraceroute
	RevtrHop
	RevtrResponse
	Time
	RTT
	TracerouteMeasurement
	TracerouteArg
	TracerouteHop
	Traceroute
	TracerouteTime
	UpdateResponse
	VantagePoint
	VPRequest
	VPReturn
*/
package datamodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type IResponseType int32

const (
	IResponseType_NONE_FOUND IResponseType = 0
	IResponseType_TOKEN      IResponseType = 1
	IResponseType_PATH       IResponseType = 2
	IResponseType_ERROR      IResponseType = 3
)

var IResponseType_name = map[int32]string{
	0: "NONE_FOUND",
	1: "TOKEN",
	2: "PATH",
	3: "ERROR",
}
var IResponseType_value = map[string]int32{
	"NONE_FOUND": 0,
	"TOKEN":      1,
	"PATH":       2,
	"ERROR":      3,
}

func (x IResponseType) String() string {
	return proto.EnumName(IResponseType_name, int32(x))
}
func (IResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Hop struct {
	Ip  uint32 `protobuf:"varint,1,opt,name=Ip" json:"Ip,omitempty"`
	Ttl uint32 `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *Hop) Reset()                    { *m = Hop{} }
func (m *Hop) String() string            { return proto.CompactTextString(m) }
func (*Hop) ProtoMessage()               {}
func (*Hop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Path struct {
	Address uint32 `protobuf:"varint,1,opt,name=address" json:"address,omitempty"`
	Dest    uint32 `protobuf:"varint,2,opt,name=dest" json:"dest,omitempty"`
	Hops    []*Hop `protobuf:"bytes,3,rep,name=hops" json:"hops,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Path) GetHops() []*Hop {
	if m != nil {
		return m.Hops
	}
	return nil
}

type IntersectionRequest struct {
	Address      uint32 `protobuf:"varint,1,opt,name=address" json:"address,omitempty"`
	Dest         uint32 `protobuf:"varint,2,opt,name=dest" json:"dest,omitempty"`
	Staleness    int64  `protobuf:"varint,3,opt,name=staleness" json:"staleness,omitempty"`
	UseAliases   bool   `protobuf:"varint,4,opt,name=use_aliases" json:"use_aliases,omitempty"`
	IgnoreSource bool   `protobuf:"varint,5,opt,name=ignore_source" json:"ignore_source,omitempty"`
	Src          uint32 `protobuf:"varint,6,opt,name=src" json:"src,omitempty"`
}

func (m *IntersectionRequest) Reset()                    { *m = IntersectionRequest{} }
func (m *IntersectionRequest) String() string            { return proto.CompactTextString(m) }
func (*IntersectionRequest) ProtoMessage()               {}
func (*IntersectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type IntersectionResponse struct {
	Type  IResponseType `protobuf:"varint,1,opt,name=type,enum=datamodel.IResponseType" json:"type,omitempty"`
	Token uint32        `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	Path  *Path         `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Error string        `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *IntersectionResponse) Reset()                    { *m = IntersectionResponse{} }
func (m *IntersectionResponse) String() string            { return proto.CompactTextString(m) }
func (*IntersectionResponse) ProtoMessage()               {}
func (*IntersectionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IntersectionResponse) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

type TokenRequest struct {
	Token uint32 `protobuf:"varint,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TokenResponse struct {
	Token uint32        `protobuf:"varint,1,opt,name=token" json:"token,omitempty"`
	Type  IResponseType `protobuf:"varint,2,opt,name=type,enum=datamodel.IResponseType" json:"type,omitempty"`
	Path  *Path         `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Error string        `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TokenResponse) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func init() {
	proto.RegisterType((*Hop)(nil), "datamodel.Hop")
	proto.RegisterType((*Path)(nil), "datamodel.Path")
	proto.RegisterType((*IntersectionRequest)(nil), "datamodel.IntersectionRequest")
	proto.RegisterType((*IntersectionResponse)(nil), "datamodel.IntersectionResponse")
	proto.RegisterType((*TokenRequest)(nil), "datamodel.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "datamodel.TokenResponse")
	proto.RegisterEnum("datamodel.IResponseType", IResponseType_name, IResponseType_value)
}

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0xcd, 0x9f, 0xae, 0x9b, 0x9b, 0x4d, 0x37, 0xce, 0x2a, 0xe4, 0xc1, 0x95, 0x25, 0x0f,
	0xb2, 0x08, 0x26, 0x50, 0x3f, 0x80, 0x88, 0x46, 0xb6, 0x08, 0x89, 0x64, 0xb3, 0xcf, 0x65, 0x9a,
	0x5c, 0xda, 0x60, 0x9a, 0x89, 0x33, 0x13, 0x41, 0x7c, 0xf1, 0xa3, 0x3b, 0x99, 0xa6, 0xa1, 0x7d,
	0x2a, 0x3e, 0xce, 0x3d, 0xe7, 0x9e, 0xf9, 0x9d, 0x61, 0x20, 0xd9, 0xd4, 0x72, 0xdb, 0xaf, 0xa3,
	0x92, 0xed, 0xe2, 0x34, 0x79, 0x7a, 0xff, 0x98, 0x3e, 0xc6, 0x39, 0xfe, 0x42, 0x2e, 0xb0, 0xe0,
	0xb4, 0x44, 0xce, 0x7a, 0x89, 0x71, 0x45, 0x25, 0xdd, 0xb1, 0x0a, 0x9b, 0xb8, 0x6e, 0xe5, 0xa0,
	0x95, 0x92, 0xe3, 0xcf, 0x1e, 0x85, 0x8c, 0x3a, 0xce, 0x24, 0x23, 0xce, 0xe4, 0x08, 0xdf, 0x80,
	0xf5, 0xc0, 0x3a, 0x02, 0x60, 0x2e, 0xbb, 0xc0, 0xb8, 0x33, 0xee, 0x3d, 0xe2, 0x82, 0x25, 0x65,
	0x13, 0x98, 0xc3, 0x21, 0xfc, 0x0c, 0xf6, 0x77, 0x2a, 0xb7, 0xe4, 0x1a, 0x9e, 0xd3, 0xaa, 0xe2,
	0x28, 0xc4, 0xe8, 0xba, 0x02, 0xbb, 0x52, 0x89, 0x7b, 0x1b, 0x79, 0x0d, 0xf6, 0x96, 0x75, 0x22,
	0xb0, 0xee, 0xac, 0x7b, 0x77, 0x31, 0x8f, 0xa6, 0x0b, 0x22, 0x95, 0x1e, 0xfe, 0x35, 0xe0, 0x66,
	0x79, 0x40, 0xa9, 0x59, 0x9b, 0xef, 0x69, 0xce, 0x85, 0xbe, 0x00, 0x47, 0x48, 0xda, 0x60, 0x3b,
	0x18, 0x2c, 0x35, 0xb2, 0xc8, 0x0d, 0xb8, 0xbd, 0xc0, 0x15, 0x6d, 0x6a, 0x2a, 0x50, 0x04, 0xb6,
	0x1a, 0x5e, 0x92, 0x57, 0xe0, 0xd5, 0x9b, 0x96, 0x71, 0x5c, 0x09, 0xd6, 0xf3, 0x12, 0x83, 0x99,
	0x1e, 0xab, 0x1e, 0x82, 0x97, 0xc1, 0x85, 0xee, 0xf1, 0x07, 0x5e, 0x9e, 0x12, 0x88, 0x8e, 0xb5,
	0x02, 0xc9, 0x5b, 0xb0, 0xe5, 0xef, 0x0e, 0xf5, 0xfd, 0xf3, 0x45, 0x70, 0x04, 0xbe, 0x3c, 0x78,
	0x0a, 0xa5, 0x13, 0x0f, 0x66, 0x92, 0xfd, 0xc0, 0x76, 0x44, 0xbb, 0x05, 0xbb, 0x53, 0xcf, 0xa2,
	0xa9, 0xdc, 0xc5, 0xf5, 0xd1, 0x9a, 0x7e, 0x2d, 0xe5, 0x46, 0xce, 0x19, 0xd7, 0x80, 0x4e, 0x78,
	0x0b, 0x57, 0xc5, 0xb0, 0x7c, 0xe8, 0x3d, 0x85, 0xe9, 0xd6, 0xa1, 0x04, 0x6f, 0x94, 0x47, 0xa8,
	0x53, 0x7d, 0x62, 0x34, 0xcf, 0x30, 0xfe, 0x17, 0xd4, 0xbb, 0x8f, 0xe0, 0x9d, 0xae, 0xcf, 0x01,
	0xd2, 0x2c, 0x4d, 0x56, 0x5f, 0xb3, 0xa7, 0xf4, 0x8b, 0xff, 0x8c, 0x38, 0x30, 0x2b, 0xb2, 0x6f,
	0x49, 0xea, 0x1b, 0xe4, 0x52, 0xfd, 0x82, 0x4f, 0xc5, 0x83, 0x6f, 0x0e, 0xc3, 0x24, 0xcf, 0xb3,
	0xdc, 0xb7, 0xd6, 0x17, 0xfa, 0x33, 0x7d, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x21, 0xde, 0x81,
	0x6c, 0x95, 0x02, 0x00, 0x00,
}
