/*
Copyright (c) 2015, Northeastern University
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Northeastern University nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL Northeastern University BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/mtype.proto
// DO NOT EDIT!

/*
Package datamodel is a generated protocol buffer package.

It is generated from these files:
	github.com/NEU-SNS/ReverseTraceroute/datamodel/mtype.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/ping.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/recspoof.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/register.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/service.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/time.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/traceroute.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/update.proto
	github.com/NEU-SNS/ReverseTraceroute/datamodel/vantagepoint.proto

It has these top-level messages:
*/
package datamodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type MType int32

const (
	MType_PING       MType = 0
	MType_STATS      MType = 1
	MType_TRACEROUTE MType = 2
)

var MType_name = map[int32]string{
	0: "PING",
	1: "STATS",
	2: "TRACEROUTE",
}
var MType_value = map[string]int32{
	"PING":       0,
	"STATS":      1,
	"TRACEROUTE": 2,
}

func (x MType) String() string {
	return proto.EnumName(MType_name, int32(x))
}

func init() {
	proto.RegisterEnum("datamodel.MType", MType_name, MType_value)
}
