// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/recspoof.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TSType int32

const (
	TSType_TSOnly    TSType = 0
	TSType_TSAndAddr TSType = 1
	TSType_TSPreSpec TSType = 3
)

var TSType_name = map[int32]string{
	0: "TSOnly",
	1: "TSAndAddr",
	3: "TSPreSpec",
}
var TSType_value = map[string]int32{
	"TSOnly":    0,
	"TSAndAddr": 1,
	"TSPreSpec": 3,
}

func (x TSType) String() string {
	return proto.EnumName(TSType_name, int32(x))
}
func (TSType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type RecSpoof struct {
	Spoofs []*Spoof `protobuf:"bytes,1,rep,name=spoofs" json:"spoofs,omitempty"`
}

func (m *RecSpoof) Reset()                    { *m = RecSpoof{} }
func (m *RecSpoof) String() string            { return proto.CompactTextString(m) }
func (*RecSpoof) ProtoMessage()               {}
func (*RecSpoof) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *RecSpoof) GetSpoofs() []*Spoof {
	if m != nil {
		return m.Spoofs
	}
	return nil
}

type Spoof struct {
	Ip  uint32 `protobuf:"varint,1,opt,name=ip" json:"ip,omitempty"`
	Id  uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Sip uint32 `protobuf:"varint,3,opt,name=sip" json:"sip,omitempty"`
	Dst uint32 `protobuf:"varint,4,opt,name=dst" json:"dst,omitempty"`
}

func (m *Spoof) Reset()                    { *m = Spoof{} }
func (m *Spoof) String() string            { return proto.CompactTextString(m) }
func (*Spoof) ProtoMessage()               {}
func (*Spoof) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type SpoofedProbes struct {
	Probes []*Probe `protobuf:"bytes,1,rep,name=probes" json:"probes,omitempty"`
}

func (m *SpoofedProbes) Reset()                    { *m = SpoofedProbes{} }
func (m *SpoofedProbes) String() string            { return proto.CompactTextString(m) }
func (*SpoofedProbes) ProtoMessage()               {}
func (*SpoofedProbes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *SpoofedProbes) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

type SpoofedProbesResponse struct {
}

func (m *SpoofedProbesResponse) Reset()                    { *m = SpoofedProbesResponse{} }
func (m *SpoofedProbesResponse) String() string            { return proto.CompactTextString(m) }
func (*SpoofedProbesResponse) ProtoMessage()               {}
func (*SpoofedProbesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type Probe struct {
	SpooferIp uint32       `protobuf:"varint,1,opt,name=spoofer_ip" json:"spoofer_ip,omitempty"`
	ProbeId   uint32       `protobuf:"varint,2,opt,name=probe_id" json:"probe_id,omitempty"`
	Src       uint32       `protobuf:"varint,4,opt,name=src" json:"src,omitempty"`
	Dst       uint32       `protobuf:"varint,5,opt,name=dst" json:"dst,omitempty"`
	Id        uint32       `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
	SeqNum    uint32       `protobuf:"varint,7,opt,name=seq_num" json:"seq_num,omitempty"`
	RR        *RecordRoute `protobuf:"bytes,8,opt,name=r_r" json:"r_r,omitempty"`
	Ts        *TimeStamp   `protobuf:"bytes,9,opt,name=ts" json:"ts,omitempty"`
	SenderIp  uint32       `protobuf:"varint,10,opt,name=sender_ip" json:"sender_ip,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Probe) GetRR() *RecordRoute {
	if m != nil {
		return m.RR
	}
	return nil
}

func (m *Probe) GetTs() *TimeStamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type RecordRoute struct {
	Hops []uint32 `protobuf:"varint,1,rep,packed,name=hops" json:"hops,omitempty"`
}

func (m *RecordRoute) Reset()                    { *m = RecordRoute{} }
func (m *RecordRoute) String() string            { return proto.CompactTextString(m) }
func (*RecordRoute) ProtoMessage()               {}
func (*RecordRoute) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type TimeStamp struct {
	Type   TSType   `protobuf:"varint,1,opt,name=type,enum=datamodel.TSType" json:"type,omitempty"`
	Stamps []*Stamp `protobuf:"bytes,2,rep,name=stamps" json:"stamps,omitempty"`
}

func (m *TimeStamp) Reset()                    { *m = TimeStamp{} }
func (m *TimeStamp) String() string            { return proto.CompactTextString(m) }
func (*TimeStamp) ProtoMessage()               {}
func (*TimeStamp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *TimeStamp) GetStamps() []*Stamp {
	if m != nil {
		return m.Stamps
	}
	return nil
}

type Stamp struct {
	Time uint32 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Ip   uint32 `protobuf:"varint,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Stamp) Reset()                    { *m = Stamp{} }
func (m *Stamp) String() string            { return proto.CompactTextString(m) }
func (*Stamp) ProtoMessage()               {}
func (*Stamp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

type NotifyRecSpoofResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *NotifyRecSpoofResponse) Reset()                    { *m = NotifyRecSpoofResponse{} }
func (m *NotifyRecSpoofResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyRecSpoofResponse) ProtoMessage()               {}
func (*NotifyRecSpoofResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

type ReceiveSpoofedProbesResponse struct {
}

func (m *ReceiveSpoofedProbesResponse) Reset()                    { *m = ReceiveSpoofedProbesResponse{} }
func (m *ReceiveSpoofedProbesResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiveSpoofedProbesResponse) ProtoMessage()               {}
func (*ReceiveSpoofedProbesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func init() {
	proto.RegisterType((*RecSpoof)(nil), "datamodel.RecSpoof")
	proto.RegisterType((*Spoof)(nil), "datamodel.Spoof")
	proto.RegisterType((*SpoofedProbes)(nil), "datamodel.SpoofedProbes")
	proto.RegisterType((*SpoofedProbesResponse)(nil), "datamodel.SpoofedProbesResponse")
	proto.RegisterType((*Probe)(nil), "datamodel.Probe")
	proto.RegisterType((*RecordRoute)(nil), "datamodel.RecordRoute")
	proto.RegisterType((*TimeStamp)(nil), "datamodel.TimeStamp")
	proto.RegisterType((*Stamp)(nil), "datamodel.Stamp")
	proto.RegisterType((*NotifyRecSpoofResponse)(nil), "datamodel.NotifyRecSpoofResponse")
	proto.RegisterType((*ReceiveSpoofedProbesResponse)(nil), "datamodel.ReceiveSpoofedProbesResponse")
	proto.RegisterEnum("datamodel.TSType", TSType_name, TSType_value)
}

var fileDescriptor2 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0x92, 0xc6, 0x63, 0x02, 0xae, 0x05, 0xc5, 0x07, 0x44, 0xcb, 0x72, 0xa0, 0x42,
	0x90, 0x88, 0x70, 0xe2, 0xc0, 0xa1, 0x95, 0xb8, 0x86, 0x2a, 0x0e, 0x17, 0x2e, 0x51, 0xe2, 0x9d,
	0x52, 0x4b, 0x8d, 0x77, 0x99, 0xdd, 0x54, 0xca, 0xcf, 0xf1, 0x6d, 0x8c, 0xc7, 0x24, 0x75, 0xd5,
	0xdc, 0x66, 0x76, 0xde, 0xbe, 0x79, 0xf3, 0x66, 0xe0, 0xdb, 0xef, 0xd2, 0xdf, 0x6c, 0x56, 0xa3,
	0xc2, 0xac, 0xc7, 0xd3, 0xef, 0x3f, 0x3f, 0xe5, 0xd3, 0x7c, 0x3c, 0xc3, 0x3b, 0x24, 0x87, 0x73,
	0x5a, 0x16, 0x48, 0x66, 0xe3, 0x71, 0xac, 0x97, 0x7e, 0xb9, 0x36, 0x1a, 0x6f, 0xc7, 0x84, 0x85,
	0xb3, 0xc6, 0x5c, 0x8f, 0x2c, 0x19, 0x6f, 0xd2, 0x68, 0x5f, 0x51, 0x1f, 0x61, 0x30, 0xc3, 0x22,
	0xaf, 0x8b, 0xe9, 0x19, 0xf4, 0x05, 0xe5, 0xb2, 0xe0, 0x2c, 0x3c, 0x8f, 0x27, 0xc9, 0x68, 0x8f,
	0x1b, 0x09, 0x42, 0x7d, 0x85, 0x5e, 0x03, 0x05, 0xe8, 0x94, 0x96, 0x61, 0xc1, 0xf9, 0x50, 0x62,
	0x9d, 0x75, 0x24, 0x8e, 0x21, 0x74, 0x5c, 0x08, 0x77, 0x89, 0x76, 0x3e, 0xeb, 0xd6, 0x89, 0xfa,
	0x0c, 0x43, 0xf9, 0x8a, 0xfa, 0x8a, 0xcc, 0x0a, 0x5d, 0xdd, 0xcd, 0x4a, 0x74, 0xa0, 0x9b, 0x40,
	0xd4, 0x2b, 0x78, 0xf9, 0xe0, 0xcb, 0x0c, 0x59, 0x5e, 0xe5, 0x50, 0xfd, 0x0d, 0xa0, 0x27, 0x4f,
	0x29, 0x37, 0x17, 0xc9, 0x48, 0x8b, 0xbd, 0x9e, 0x04, 0x06, 0x42, 0xbc, 0x78, 0xa0, 0x8a, 0x8a,
	0x46, 0xc8, 0x4e, 0x55, 0xaf, 0xa5, 0xbd, 0x2f, 0xf1, 0x73, 0x38, 0x72, 0xf8, 0x67, 0x51, 0x6d,
	0xd6, 0xd9, 0x91, 0x3c, 0xbc, 0x83, 0x90, 0x16, 0x94, 0x0d, 0x38, 0x89, 0x27, 0x27, 0x2d, 0x79,
	0xec, 0x98, 0x21, 0x3d, 0xab, 0x4d, 0xe6, 0x31, 0x3a, 0xde, 0x65, 0x91, 0x60, 0x5e, 0xb4, 0x30,
	0xf3, 0x72, 0x8d, 0x39, 0x27, 0x36, 0x3d, 0x86, 0xc8, 0x61, 0xa5, 0x1b, 0x89, 0x20, 0x66, 0x9c,
	0x42, 0xdc, 0xe6, 0x48, 0xa0, 0x7b, 0x63, 0x6c, 0x63, 0xc4, 0xf0, 0xb2, 0x93, 0x04, 0x6a, 0x0a,
	0xd1, 0x3d, 0xc1, 0x29, 0x74, 0xfd, 0xd6, 0xa2, 0x8c, 0xf7, 0x6c, 0x72, 0xdc, 0x6e, 0x92, 0xcf,
	0xb9, 0x20, 0x8b, 0xab, 0x91, 0x8e, 0xe7, 0x7d, 0xb4, 0xb8, 0xba, 0xa0, 0xde, 0xf2, 0xe2, 0x84,
	0xeb, 0x29, 0x73, 0x31, 0x71, 0x6b, 0x75, 0xb6, 0x31, 0x49, 0xbd, 0x87, 0x93, 0xa9, 0xf1, 0xe5,
	0xf5, 0x76, 0x77, 0x0f, 0x3b, 0xbb, 0xd3, 0x21, 0xf4, 0x90, 0xc8, 0x90, 0x7c, 0x8a, 0xd4, 0x1b,
	0x78, 0xcd, 0x10, 0x2c, 0xef, 0xf0, 0xe0, 0x76, 0x3e, 0x4c, 0xa0, 0xff, 0x5f, 0x17, 0xd4, 0xd1,
	0x8f, 0xea, 0x76, 0x9b, 0x3c, 0x61, 0x92, 0x68, 0x9e, 0x5f, 0x54, 0xfa, 0x42, 0x6b, 0x4a, 0x82,
	0x26, 0xbd, 0x22, 0xa6, 0xc0, 0x22, 0x09, 0x2f, 0xe3, 0x5f, 0xf7, 0x37, 0xb9, 0xea, 0xcb, 0x95,
	0x7e, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x75, 0xce, 0xb2, 0xcb, 0xe6, 0x02, 0x00, 0x00,
}
