// Code generated by protoc-gen-go.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/reverse_traceroute.proto
// DO NOT EDIT!

package datamodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RevtrMeasurement struct {
	Src       string `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Dst       string `protobuf:"bytes,2,opt,name=dst" json:"dst,omitempty"`
	Staleness uint32 `protobuf:"varint,3,opt,name=staleness" json:"staleness,omitempty"`
}

func (m *RevtrMeasurement) Reset()         { *m = RevtrMeasurement{} }
func (m *RevtrMeasurement) String() string { return proto.CompactTextString(m) }
func (*RevtrMeasurement) ProtoMessage()    {}

type RevtrRequest struct {
	Revtrs []*RevtrMeasurement `protobuf:"bytes,1,rep,name=revtrs" json:"revtrs,omitempty"`
}

func (m *RevtrRequest) Reset()         { *m = RevtrRequest{} }
func (m *RevtrRequest) String() string { return proto.CompactTextString(m) }
func (*RevtrRequest) ProtoMessage()    {}

func (m *RevtrRequest) GetRevtrs() []*RevtrMeasurement {
	if m != nil {
		return m.Revtrs
	}
	return nil
}

type RevtrResponse struct {
}

func (m *RevtrResponse) Reset()         { *m = RevtrResponse{} }
func (m *RevtrResponse) String() string { return proto.CompactTextString(m) }
func (*RevtrResponse) ProtoMessage()    {}
